[workspace]
members = ["engine_macros"]

[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "engine-cli"
path = "src/main.rs"

[dependencies]
engine_macros = { path = "engine_macros" }
pyo3 = { version = "0.28.2", features = ["extension-module"] }
